# Generated by Django 3.1.7 on 2021-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша почта')),
                ('telephone', models.CharField(max_length=20, verbose_name='Ваш номер телефона')),
                ('university', models.CharField(max_length=50, verbose_name='Ваш Университет')),
                ('discipline', models.CharField(max_length=50, verbose_name='Дисциплина, в котором нуждаетесь в менторе')),
            ],
        ),
    ]
